config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :friend_requests, only: [:index, :create ] do
    member do
      post 'accept'
      delete 'cancel'
      delete 'decline'
    end
  end

  resources :friend_ships, only: [:index, :destroy]


  resources :posts do
    resources :comments, module: :posts
    resources :likes, module: :posts
  end

  resources :comments do
    resources :comments, module: :comments
    resources :likes, module: :comments
  end

  # Defines the root path route ("/")
   root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy

  validates_presence_of :body
end

app/controllers/comments/comments_controller.rb
class Comments::CommentsController < ::CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = Comment.find(params[:comment_id])
  end
end

app/controllers/comments/likes_controller.rb
class Comments::LikesController < ::LikesController
  before_action :set_likable

  private
  def set_likable
    @likable = Comment.find(params[:comment_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, except: [:create]

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice]= 'You created a comment!'
    else
      flash[:alert]= "Error saving comment"
    end
    redirect_back fallback_location: root_path
  end

  def update
    if @comment&.update(comment_params)
      flash[:notice]= "Changes saved, comment has been updated!"
      redirect_back fallback_location: root_path
    else
      flash[:alert]= "Error updating"
      render :edit
    end
  end

  def show
    @comment
  end

  def edit
  end

  def destroy
    if @comment&.destroy
     flash[:notice]= "Comment deleted!"
    else
     flash[:alert]= "Error deleting comment"
    end
    # https://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_to
    redirect_back fallback_location: root_path, status: 303
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_comment
    @comment= Comment.find(params[:id])
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < ::CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = Post.find(params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_links.html.erb
<% if comment.user == current_user %>
  <nav class="level is-mobile">
    <div class="level-left">
      <p class="level-item">
        <small> <%= link_to edit_comment_path(comment) do %>
                  <i class="fa-solid fa-pen-to-square"></i>
                <% end %> |
                <%= link_to comment_path(comment), data: {"turbo-method": :delete}, class: "trash" do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
          </small>
        </p>
      </div>
    </nav>
  <% end %>

app/views/comments/_display_comment.html.erb
<div class="box">
  <article class="media">
    <figure class="media-left">
      <%= image_tag user_avatar(comment.user, 54) %>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= link_to comment.user.name, user_path(comment.user), class: "has-text-info-dark" %></strong> -
          <small><%= time_ago_in_words(comment.created_at) %> ago</small>
        <br>
          <%= comment.body %>
        </p>

        <nav class="level is-mobile">
          <div class="level-left">
            <p class="level-item like-button">
              <%= render "likes/like_button", likable: comment %>
            </p>
            <p class= "level-item comments">
              <%= link_to comment_path(comment), class: "hidden-button has-text-info-dark" do %>
                <i class="fa-solid fa-comment"></i> <small><%= comment.comments.count %> Comment(s)</small>
              <% end %>
            </p>
           </div>
          </nav>
         </div>
        </div>
     </article>
   </div>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new] do |f| %>
  <article class="media">
    <figure class="media-left">
      <%= image_tag user_avatar(current_user, 64) %>
    </figure>
    <div class="media-content">
      <div class="field">
        <div class="control comment-box">
          <%= f.text_area :body, label: false, input_html: { class: "textarea" }, wrapper: false, placeholder: "Add a comment" %>
        </div>
      </div>
      <nav class="level">
        <div class="level-left">
          <div class="level-item">
            <%= f.submit "Comment", class: "button is-primary" %>
          </div>
        </div>
      </nav>
    </div>
  </article>
<% end %>

app/views/comments/_replies.html.erb
<% commentable.comments.each do |comment| %>
  <%= render "comments/display_comment", comment: comment %>
  <%= render "comments/comment_links", comment: comment %>
<% end %>

app/views/comments/edit.html.erb
<div class="section">
  <div class="container">
    <div class="subtitle is-6 has-text-centered">Editing Comment</div>
      <%= form_with(model: @comment, local: true) do |f| %>
        <article class="media">
          <figure class="media-left">
            <%= image_tag user_avatar(current_user, 64) %>
          </figure>
          <div class="media-content">
            <div class="field">
              <div class="control comment-box">
                <%= f.text_area :body, label: false, input_html: { class: "textarea" }, wrapper: false, placeholder: "Add a comment" %>
              </div>
            </div>
            <nav class="level">
              <div class="level-left">
                <div class="level-item">
                  <%= f.submit "Update Comment", data: {"turbo-method": :patch}, class: "button is-primary" %>
               </div>
              </div>
            </nav>
          </div>
         </article>
       <% end %>

       <nav class="navbar is-fixed-bottom">
       <div class="navbar-menu">
         <div class="navbar-item">
           <div class="field is-grouped">
             <p class="control">
               <%= link_to 'Cancel', root_path, class: "button is-dark" %>
             </p>
         </div>
       </div>
       </nav>
      </div>
    </div>

app/views/comments/new.html.erb
<div class="section">
  <div class="container">
    <%= render "form", comment: @comment %>

    <nav class="navbar is-fixed-bottom">
      <div class="navbar-menu">
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'Cancel', root_path, class: "button is-dark" %>
            </p>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/comments/show.html.erb
<div class="section">
  <div class="comment-container">
    <%= render "comments/display_comment", comment: @comment %>
    <%= render "comments/comment_links", comment: @comment %>

    <div class="comments-container">
       <%= render "comments/replies", commentable: @comment %>
    </div>

    <div class="comment-form">
       <%= render "comments/form", commentable: @comment %>
    </div>
  </div>

  <nav class="navbar is-fixed-bottom">
   <div class="navbar-menu">
     <div class="navbar-item">
       <div class="field is-grouped">
         <p class="control">
           <%= link_to 'Back', root_path, class: "button is-dark" %>
         </p>
     </div>
   </div>
 </nav>
 </div>