config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :friend_requests, only: [:index, :create ] do
    member do
      post 'accept'
      delete 'cancel'
      delete 'decline'
    end
  end

  resources :friend_ships, only: [:index, :destroy]


  resources :posts do
    resources :comments, module: :posts
    resources :likes, module: :posts
  end

  resources :comments do
    resources :comments, module: :comments
    resources :likes, module: :comments
  end

  # Defines the root path route ("/")
   root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  is_gravtastic :size => 100

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_one_attached :avatar

  has_many :sent_friend_requests,
           class_name: 'FriendRequest',
           foreign_key: "sender_id",
           dependent: :destroy

  has_many :received_friend_requests,
           class_name: 'FriendRequest',
           foreign_key: "receiver_id",
           dependent: :destroy

  has_many :friend_ships,
    ->(user) { FriendShipsQuery.both_ways(user_id: user.id) },
    inverse_of: :user,
    dependent: :destroy

  has_many :friends,
    ->(user) { UsersQuery.friends(user_id: user.id, scope: true) },
    through: :friend_ships,
    dependent: :destroy

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy


  def self.from_omniauth(auth)
    oauth_user = where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def formatted_birthday
    birthday.strftime('%m/%d')
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
   skip_before_action :verify_authenticity_token, only: [:facebook]

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    send_welcome_email if @user.new_record? && @user.save

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  after_action :send_welcome_email, only: :create, if: -> { @user.persisted? }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice]= "Changes saved, profile updated!"
      redirect_to @user
    else
      flash[:error]= "Error updating"
      render :edit
    end
  end

 private

  def user_params
    params.require(:user)
      .permit(:location, :profession, :education, :relationship, :birthday,
         :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user, size)
    if user.avatar.attached?
      user.avatar.variant(resize_to_limit: [size,size])
    else
      user.gravatar_url(size: size)
    end
  end

  def formatted_birthday(user)
    user.birthday.strftime('%m/%d')
  end
end

app/views/users/_friend_status.html.erb
<% sent_request= current_user.sent_friend_requests.find_by(receiver: user) %>
<% received_request =  current_user.received_friend_requests.find_by(sender: user) %>
<% friendship = FriendShip.where(user: user, friend: current_user).or(FriendShip.where(user: current_user, friend: user)).first %>

<% if current_user.friends.include?(user) %>
  <p class="level-item"><%= link_to "Remove Friend", friend_ship_path(friendship), data: { "turbo-method": :delete }, class: "button is-danger" %></p>
<% elsif sent_request.present? %>
  <p class="level-item"><%= link_to "Cancel Request", cancel_friend_request_path(sent_request), data: { "turbo-method": :delete }, class: "button is-danger" %></p>
<% elsif received_request.present? %>
  <p class="level-item"><%= render "friend_requests/accept_or_decline_request", friend_request: received_request %></p>
<% else %>
  <p class="level-item"><%= link_to "Add Friend", friend_requests_path(receiver_id: user.id), data: { "turbo-method": :post }, class: "button is-primary" %></p>
<% end %>

app/views/users/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <div class="title is-4">Update Profile</div>
          <%= form_with(model: @user, local: true) do |f| %>

            <div class="field">
              <div class="control">
                <div class="row">
                  <div class="columns">
                    <div class="column">
                        <%= image_tag user_avatar(@user, 300) %>
                    </div>

                    <div class="column">
                     <%= f.file_field :avatar %>
                   </div>
                  </div>
                 </div>
                </div>
               </div>

            <div class="field">
                 <div class="control">
                   <label for= 'location'>Location:</label>
                   <%= f.text_field :location, autofocus: true %>
                 </div>
               </div>

            <div class="field">
              <div class="control">
                <label for= 'profession'>Profession:</label>
                <%= f.text_field :profession, autofocus: true %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <label for= 'education'>Education:</label>
                <%= f.text_field :education, autofocus: true %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <label for= 'relationship'>Relationship Status:</label>
                <%= f.text_field :relationship, autofocus: true %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <label for= 'birthday'>Birthday:</label>
                <%= f.date_select :birthday, autofocus: true, discard_year: true, prompt: true %>
              </div>
            </div>

            <%= f.submit "Update", class: "button is-info" %>

          <% end %>
        </div>
      </div>
    </div>
  </div>

  <nav class="navbar is-fixed-bottom">
    <div class="navbar-menu">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <%= link_to 'Cancel', root_path, class: "button is-dark" %>
          </p>
      </div>
    </div>
  </nav>

app/views/users/index.html.erb
<div class= "section">
  <div class= "container">
    <div class= "columns is-centered">
      <div class= "column is-three-fifths">
        <div class= "title is-5 has-text-centered">Odin's Club Members</div>
          <ul>
            <% @users.each do |user| %>
              <% next if user == current_user %>
              <li> <div class="level">
                     <div class="level-left">
                       <p class="level-item"><%= image_tag user_avatar(user, 75) %></p>
                       <p class="level-item"><%= link_to user.name, user_path(user), class: "has-text-info-dark" %></p>
                     </div>

                     <div class="level-right">
                       <%= render "friend_status", user: user %>
                      </div>
                    </div><br />
               </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column user-info">
        <article class="media">
          <figure class="media-left">
            <%= image_tag user_avatar(@user, 100) %>
          </figure>
          <div class="media-content">
            <div class="content has-text-info-dark">
              <p>
                <strong><%= @user.name %></strong>
              </p>
              <p>
                <% if @user.location.present? %>
                  <p> <strong>Location:</strong> <%= @user.location %> </p>
                <% end %>

                <% if @user.profession.present? %>
                  <p> <strong>Profession:</strong> <%= @user.profession %> </p>
                <% end %>

                <% if @user.education.present? %>
                  <p> <strong>Education:</strong> <%= @user.education %> </p>
                <% end %>

                <% if @user.relationship.present? %>
                  <p> <strong>Relationship Status:</strong>
                    <%= @user.relationship %> </p>
                <% end %>

                <% if @user.birthday.present? %>
                  <p> <strong>Birthday:</strong>
                    <%= @user.formatted_birthday %> </p>
                <% end %>

                <% if @user == current_user %>
                  <p> <%= link_to "Edit Info", edit_user_path(@user),
                    class: "has-text-info-dark" %> </p>
                <% end %>
             </div>
            </div>
           </article>
          </div>


          <div class="column user-friends">
            <% if @user == current_user %>
              <p> <%= link_to "My Friends", friend_ships_path, class: "button is-info is-inverted" %> </p> <br>
              <p> <%= link_to "Pending Friend Requests", friend_requests_path, class: "button is-info is-inverted" %> </p>
            <% else %>
              <p> <%= render "friend_status", user: @user %> </p>
            <% end %>
           </div>
          </div>
         </div>

        <div class="user-posts">
          <div class="title is-6">Posts</div>
           <% if @user.posts.any? %>
             <% @user.posts.each do |post| %>
               <%= render "posts/post_content", post: post %>
               <%= render "posts/post_links", post: post %>
             <% end %>
           <% else %>
             <p> No posts yet! </p>
           <% end %>
        </div>
      </div>