config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :friend_requests, only: [:index, :create ] do
    member do
      post 'accept'
      delete 'cancel'
      delete 'decline'
    end
  end

  resources :friend_ships, only: [:index, :destroy]


  resources :posts do
    resources :comments, module: :posts
    resources :likes, module: :posts
  end

  resources :comments do
    resources :comments, module: :comments
    resources :likes, module: :comments
  end

  # Defines the root path route ("/")
   root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy

  validates_presence_of :body
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < ::CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = Post.find(params[:post_id])
  end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ::LikesController
  before_action :set_likable

  private
  def set_likable
    @likable = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:index, :create, :new]

  def index
    @post = Post.new
    friend_ids = current_user.friends.pluck(:id)
    @posts = Post.where(user_id: friend_ids).or(Post.where(user_id: current_user.id)).order(created_at: :desc)
  end 

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
     flash[:notice]= 'You created a new post!'
     redirect_to @post
    else
     flash[:alert]= "Error saving post"
     render :new
    end
  end

  def show
    @post
  end

  def edit
  end

  def destroy
    if @post&.destroy
     flash[:notice]= "Post deleted!"
    else
     flash[:notice]= "Error removing post"
    end
    redirect_to root_path, status: 303
  end

  def update
    if @post&.update(post_params)
      flash[:notice]= "Changes saved, post has been updated!"
      redirect_to @post
    else
      flash[:alert]= "Error updating post"
      render :edit
    end
  end


 private

 def post_params
   params.require(:post).permit(:body)
 end

 def set_post
   @post= Post.find(params[:id])
 end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |f| %>
  <article class="media">
    <figure class="media-left">
       <%= image_tag user_avatar(current_user, 64) %>
    </figure>
    <div class="media-content">
      <div class="field">
        <p class="control post-box">
          <%= f.text_area :body, label: false, input_html: { class: "textarea" }, wrapper: false, placeholder: "What's on your mind?" %>
        </p>
      </div>
      <nav class="level">
        <div class="level-left">
          <div class="level-item">
            <%= f.submit "Post", class: "button is-primary" %>
          </div>
        </div>
      </nav>
    </div>
  </article>
<% end %>

app/views/posts/_post_content.html.erb
<div class="box">
  <article class="media">
    <figure class="media-left">
      <%= image_tag user_avatar(post.user, 64) %>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= link_to post.user.name, user_path(post.user), class: "has-text-info-dark" %></strong> -
          <small><%= time_ago_in_words(post.created_at) %> ago</small>
        <br>
          <%= post.body %>
        </p>

        <nav class="level is-mobile">
          <div class="level-left">
            <p class="level-item like-button">
              <%= render "likes/like_button", likable: post %>
            </p>
             <p class="level-item comments">
               <%= link_to post_path(post), class: "hidden-button has-text-info-dark" do %>
                 <i class="fa-solid fa-comment"></i> <small><%= post.comments.count %> Comment(s)</small>
               <% end %>
             </p>
           </div>
         </nav>
        </div>
       </div>
    </article>
  </div>

app/views/posts/_post_links.html.erb
<% if post.user == current_user %>
  <nav class="level is-mobile">
    <div class="level-left">
      <p class="level-item">
        <small> <%= link_to edit_post_path(post) do %>
                  <i class="fa-solid fa-pen-to-square"></i>
                <% end %> |
                <%= link_to post_path(post), data: {"turbo-method": :delete}, class: "trash" do %>
                   <i class="fa-solid fa-trash-can"></i>
                <% end %>
          </small>
        </p>
      </div>
     </nav>
<% end %>

app/views/posts/edit.html.erb
<div class="section">
  <div class="form-container">
    <%= render 'form', post: @post %>
  </div>

  <nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', root_path, class: "button is-dark" %>
        </p>
    </div>
  </div>
</nav>
</div>

app/views/posts/index.html.erb
<div class="section">
  <div class="form-container">
    <div class="subtitle is-5 has-text-centered">Timeline</div>
      <%= render "form", post: @post %>
  </div>
</div>

<div class="section">
  <div class="timeline-posts">
    <% unless @posts.empty? %>
      <% @posts.each do |post| %>
        <%= render "post_content", post: post %>
        <%= render "post_links", post: post %>
       <% end %>
    <% end %>
   </div>
  </div>

app/views/posts/new.html.erb
<div class="section">
  <div class="form-container">
    <%= render 'form', post: @post %>
  </div>

  <nav class="navbar is-fixed-bottom">
    <div class="navbar-menu">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <%= link_to 'Cancel', root_path, class: "button is-dark" %>
          </p>
      </div>
    </div>
  </nav>
</div>

app/views/posts/show.html.erb
<div class="section">
  <div class="post-container">
    <%= render "post_content", post: @post %>
    <%= render "post_links", post: @post %>


   <div class="comments-container">
      <%= render "comments/replies", commentable: @post %> <br>
   </div>

   <div class="comment-form">
     <%= render "comments/form", commentable: @post %>
   </div>
  </div>

  <nav class="navbar is-fixed-bottom">
    <div class="navbar-menu">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <%= link_to 'Back', root_path, class: "button is-dark" %>
          </p>
      </div>
    </div>
  </nav>
 </div>