config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :friend_requests, only: [:index, :create ] do
    member do
      post 'accept'
      delete 'cancel'
      delete 'decline'
    end
  end

  resources :friend_ships, only: [:index, :destroy]


  resources :posts do
    resources :comments, module: :posts
    resources :likes, module: :posts
  end

  resources :comments do
    resources :comments, module: :comments
    resources :likes, module: :comments
  end

  # Defines the root path route ("/")
   root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  	<% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>

    <% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>

    <nav class="navbar is-info">
  		<div class="navbar-brand">
  		<%= link_to root_path, class: "navbar-item" do %>
  			<h1 class="title is-5 main-title">Odin's Clubhouse</h1>
  		<% end %>
			<div class="navbar-burger burger" data-target="navbarExample">
					<span></span>
					<span></span>
					<span></span>
  		</div>
  	 </div>

			<div id="navbarExample" class="navbar-menu">
        <div class="navbar-start">
          <div class="navbar-item">
            <p class="control">
              <%= link_to 'New Post', new_post_path, class: "button is-info is-inverted" %>
            </p>
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
					  <div class="field is-grouped">

            <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, user_path(current_user), class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to "Members", users_path, method: :get, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to "Notifications", friend_requests_path, method: :get, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to "Account", edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete }, class:"button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
            <% end %>
            </div>
					</div>
				</div>
			</div>
  	</nav>

    <%= yield %>
  </body>
</html>